### your general site settings
title: Eugene Song
email: esong28@outlook.com
description: Software Engineer | AWS Solutions Architect | Backend & Cloud Infrastructure
url: "https://eugenesong.github.io"
baseurl: ""

twitter_username: 
github_username: EugenSong
linkedin_username: eugenessong
facebook_username: 
instagram_username: 
pinterest_username: 
flickr_username: 
deviantart_username: 
googleplus_username: 

# path to your avatar image
avatar: /img/avatar.jpg

# for Google Analytics
google_analytics: 

# admin name for footer
admin_name: Eugene Song

# footer text
footer_text: 'Software Engineer with expertise in scalable backend architectures and cloud solutions'

# Build settings
markdown: kramdown

# Sass settings
sass:
  sass_dir: _sass
  style: compressed

# pagination
paginate: 10
paginate_path: "/page:num/"

# Jekyll plugins
plugins:
  - jekyll-paginate

# Navigation menu
nav_item:
  - { url: '/', text: 'Portfolio' }
  - { url: '/about', text: 'About' }
  - { url: '/assets/css/Eugene_Song_resume.pdf', text: 'Resume' }

# Contact form settings
enable_contact: true
contact_form_action: ""
contact_form_success_message: "Thank you for reaching out! I'll get back to you soon."

# Exclude from build
exclude:
  - README.md
  - CHANGELOG.md
  - phantom-theme-temp
  - Gemfile.lock
  - '*.gemspec'